<?php
/**
 * Language labels for plugin 'tx_t3consultancies_pi1'
 * 
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	'default' => Array (
			'All_contexts' => 'All market contexts',
			'All_types' => 'All media types',
			'back_to_list' => 'back to list',
			'remove_from_list' => 'remove from distribution list',
			'add_to_list' => 'add to distribution list',
			'download' => 'download',
			'signature' => 'signature (if automatically created signature should not be used)',
			'addreservation' => 'reserve',
			'delreservation' => 'cancel reservation',
			'reservedby' => 'prebooked by',
			'OK' => 'OK',
			'overdue' => 'overdue',
			'reminded' => 'reminded',
			'empty_list' => 'No media found.',						
			'borrownow' => 'borrow now',
			'borrow_to' => 'borrowed by:',
			'borrowdel' => 'cancel borrowing',
						
			'confirmaction_borrownow' => 'borrow now succeeds',
			'confirmaction_borrowdel' => 'cancel borrowing succeeds',
			'confirmaction_addreservation' => 'reserve succeeds',
			'confirmaction_delreservation' => 'cancel reservation succeeds',
			
			'listFieldHeader_number' => 'Callnumber:',		
			'listFieldHeader_isbn' => 'ISBN:',
			'listFieldHeader_title' => 'Title:',	
			'listFieldHeader_bibtex' => 'Literaturtyp (Bibtex):',	
			'listFieldHeader_type' => 'Media type:',	
			'listFieldHeader_author' => 'Author(en):',				
			'listFieldHeader_language' => 'Language:',	
			'listFieldHeader_context' => 'Market Context:',
			'listFieldHeader_area' => 'Thematic Area:',
			'listFieldHeader_status' => 'Status:',	
			'listFieldHeader_subtitle' => 'Subtitle:',
			'listFieldHeader_invnr' => 'InvNR:',
			'listFieldHeader_publisher' => 'Publisher:',
			'listFieldHeader_edition' => 'Edition:',
			'listFieldHeader_category' => 'Category:',
			'listFieldHeader_pubyear' => 'Publishing Year:',
			'listFieldHeader_pubdate' => 'Publishing Date:',
			'listFieldHeader_frequency' => 'Frequency:',
			'listFieldHeader_abo' => 'subscription period:',
			'listFieldHeader_comment' => 'Comment:',
			'listFieldHeader_signature' => 'Signature:',
			'listFieldHeader_download' => 'PDF File:',
			'listFieldHeader_link' => 'Path:',
			'listFieldHeader_list' => 'Distribution List:',
			'listFieldHeader_begin' => 'from:',
			'listFieldHeader_end' => 'to:',
			'listFieldHeader_info' => 'Info:',
			'listFieldHeader_borrow_to' => 'Borrowed to:',
			'listFieldHeader_person' => 'SRA-Person(s):',
			'listFieldHeader_personresult' => 'Added Person(s):',
			'listFieldHeader_invnrlookup' => 'Inventory Numbers Lookuptable:',

			
			'pi_list_browseresults_prev' => '< Previous',	
			'pi_list_browseresults_page' => 'Page',	
			'pi_list_browseresults_next' => 'Next >',	
			'pi_list_browseresults_displays' => 'Displaying medium ###DOCS_FIRST### to ###DOCS_LAST### of ###DOCS_COUNT###',	
			'pi_list_browseresults_show' => 'Show per page: ',	
			
			
			'pi_send_button' => 'Send',				
			'pi_save_button' => 'Save',
			'pi_search_phrase' => 'Search term:',	
			'pi_search_button' => 'Search',	
			'pi_search_area' => 'Area:',			
			'pi_search_status' => 'Status:',
			'pi_search_type' => 'Media type:',			
			'pi_search_status_available' => 'available',		
			'pi_search_status_reserved' => 'reserved',	
			'pi_search_status_conferred' => 'conferred',
			'tx_sramedia_types.type.I.0' => 'Book',
			'tx_sramedia_types.type.I.1' => 'CD',
			'tx_sramedia_types.type.I.2' => 'DVD',
			'tx_sramedia_types.type.I.3' => 'SRA Publication',
			'conferred' => 'conferred',
			'conferredto' => 'conferred to',
			'reserved' => 'prebooked',
			'to' => 'until',
			'nofund' => 'No book with such a ISBN fund',
			'wrong_isbn' => 'Wrong ISBN.',			

			'missing_isbn' => 'Please insert a ISBN to search for.',
			'missing_signature' => 'Missing Signature',
			'missing_title' => 'Missing title',
			'missing_invnr' => 'Missing Inventory Number',
			'missing_author' => 'Missing author',
			'missing_comment' => 'Missing context',
			'missing_area' => 'Missing area',
			'missing_sraperson' => 'Missing Person (You currently selected "SRA-Publication", therefore you must add one or more SRA-Person to the Personlist)',
			'book_savesucceded' => 'Saving succeeds!',
			'book_nodescription' => 'no description found',
			
			
	),
	'dk' => Array (
	),
	'de' => Array (
			'All_contexts' => 'Alle Rubriken',
			'All_types' => 'Alle Arten',
			'back_to_list' => 'zur&uuml;ck zur Liste',
			'remove_from_list' => 'aus Verteilerliste l&ouml;schen',
			'add_to_list' => 'in Verteilerliste aufnehmen',
			'download' => 'herunterladen',
			'addreservation' => 'reservieren',
			'delreservation' => 'Reservierung l&ouml;schen',
			'reservedby' => 'vorgemerkt von',
			'OK' => 'OK',
			'overdue' => 'f&auml;llig',
			'reminded' => 'gemahnt',
			'empty_list' => 'Keine Medien gefunden.',						
			'empty_user_list' => 'Keine Medien ausgeliehen.',						
			'borrow_to' => 'verliehen an:',
			'borrownow' => 'jetzt ausleihen',
			'borrowdel' => 'zurücklegen',
			
			'confirmaction_borrownow' => 'Das Medium wurde ausgeliehen.',
			'confirmaction_borrowdel' => 'Das Medium wurde zurückgelegt.',
			'confirmaction_addreservation' => 'Das Medium wurde reserviert.',
			'confirmaction_delreservation' => 'Die Reservierung wurde gelöscht.',
			
			'listFieldHeader_number' => 'Nummer:',	
			'listFieldHeader_sralocation' => 'Standort:',	
			'listFieldHeader_isbn' => 'ISBN (10/13):',		
			'listFieldHeader_title' => 'Titel:',	
			'listFieldHeader_booktitle' => 'Buchtitel:',	
			'listFieldHeader_volume' => 'Volume:',	
			'listFieldHeader_type' => 'Medium:',	
			'listFieldHeader_author' => 'Autor:',	
			'listFieldHeader_language' => 'Sprache:',	
			'listFieldHeader_context' => 'Rubrik:',
			'listFieldHeader_area' => 'Themenbereich:',
			'listFieldHeader_status' => 'Status:',	
			'listFieldHeader_subtitle' => 'Untertitel:',
			'listFieldHeader_invnr' => 'InvNR:',
			'listFieldHeader_publisher' => 'Verlag/Hrsg./Quelle:',
			'listFieldHeader_edition' => 'Edition:',
			'listFieldHeader_category' => 'Medium:',
			'listFieldHeader_pubyear' => 'Erschienen:',
			'listFieldHeader_pubdate' => 'Erscheinungsdatum:',
			'listFieldHeader_month' => 'Monat:',
			'listFieldHeader_editor' => 'Editor:',
			'listFieldHeader_series' => 'Serie:',
			'listFieldHeader_pages' => 'Seiten:',
			'listFieldHeader_address' => 'Adresse:',
			'listFieldHeader_organization' => 'Organisation:',
			'listFieldHeader_frequency' => 'Erscheinungsweise:',
			'listFieldHeader_abo' => 'Abo-Zeitraum:',
			'listFieldHeader_comment' => 'Abstract:',
			'listFieldHeader_note' => 'Kommentar:',
			'listFieldHeader_howpublished' => 'Howpublished:',
			'listFieldHeader_journal' => 'Journal:',
			'listFieldHeader_signature' => 'Signatur:',
			'listFieldHeader_download' => 'PDF Datei:',
			'listFieldHeader_link' => 'Pfad:',
			'listFieldHeader_list' => 'Verteilerliste:',
			'listFieldHeader_begin' => 'von:',
			'listFieldHeader_end' => 'bis:',
			'listFieldHeader_info' => 'Info:',
			'listFieldHeader_borrow_to' => 'Verliehen an:',
			'listFieldHeader_person' => 'Beteiligte SRA Mitarbeiter:',
			'listFieldHeader_sraperson' => 'SRA Mitarbeiter:',
			'listFieldHeader_personresult' => 'SRA Mitarbeiter:',
			'listFieldHeader_bibtex_type' => 'Literaturtyp:',
			'listFieldHeader_invnrlookup' => 'Inv-Nr Tabelle vorhandener Medien:',
			'listFieldHeader_signaturelookup' => 'Signaturen der Medien aus dem Themenbereich:',

			
			'pi_list_browseresults_prev' => '< zur&uuml;ck',	
			'pi_list_browseresults_page' => 'Seite',	
			'pi_list_browseresults_next' => 'vor >',	
			'pi_list_browseresults_displays' => 'Zeige Medium ###DOCS_FIRST### bis ###DOCS_LAST### von ###DOCS_COUNT###',	
			'pi_list_browseresults_show' => 'Anzeige pro Seite: ',	
			'pi_list_bookscount' => 'Ergebnisse',	
			
			'pi_send_button' => 'Senden',	
			'pi_save_button' => 'Speichern',
			'pi_search_phrase' => 'Suchtext:',	
			'pi_search_button' => 'Suchen',	
			'pi_search_area' => 'Themenbereich:',		
			'pi_search_status' => 'Status:',	
			'pi_search_type' => 'Medium:',		
			'pi_search_person' => 'Person:',		
			'pi_search_callnumber' => 'Standort:',		
			'pi_search_status_available' => 'vorhanden',		
			'pi_search_status_reserved' => 'vorgemerkt',	
			'pi_search_status_conferred' => 'verliehen',	
			'tx_sramedia_types.type.I.0' => 'Buch',
			'tx_sramedia_types.type.I.1' => 'CD',
			'tx_sramedia_types.type.I.2' => 'DVD',
			'tx_sramedia_types.type.I.3' => 'SRA Publikationen',
			'conferred' => 'verliehen',
			'conferredto' => 'verliehen an',
			'reserved' => 'vorgemerkt',
			'to' => 'bis',
			'nofund' => 'Es wurde kein Buch mit dieser ISBN gefunden.',
			'wrong_isbn' => 'Ungültige ISBN eingegeben.',
			
			'no_uid' => 'Es wurde kein Buch mit dieser ID gefunden.',
			'db_error' => 'Zurzeit ist kein Zugriff auf die Datenbank möglich. Bitte informieren Sie den Webmaster.',

			'missing_isbn' => 'Bitte tragen sie eine ISBN ein, nach der gesucht werden soll.',
			'missing_title' => 'Titel fehlt ',
			'missing_invnr' => 'Inventarnummer fehlt ',
			'missing_signature' => 'Signatur fehlt ',
			'missing_author' => 'Autor fehlt ',
			'missing_comment' => 'Kommentar fehlt ',
			'missing_area' => 'Themenbereich fehlt ',
			'missing_sraperson' => 'Fehlende Personen (Sie haben "SRA-Publikation" ausgewählt. In diesem Fall müssen Sie mind. 1 Person in die Personenliste einfügen.)',
			'book_savesucceded' => 'Speichern erfolgreich!',
			'book_nodescription' => 'keine Beschreibung gefunden',
			
			
			
	),
	'no' => Array (
	),
	'it' => Array (
	),
	'fr' => Array (
	),
	'es' => Array (
	),
	'nl' => Array (
	),
	'cz' => Array (
	),
	'pl' => Array (
	),
	'si' => Array (
	),
	'fi' => Array (
	),
	'tr' => Array (
	),
	'se' => Array (
	),
	'pt' => Array (
	),
	'ru' => Array (
	),
	'ro' => Array (
	),
);
?>
